# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zNgpvRrVuiTZSU1rjFzTWO-JfmfTtIwM
"""

import requests
from bs4 import BeautifulSoup

# Langkah 1: Mengambil konten halaman (Request)
url = "https://books.toscrape.com/"
response = requests.get(url)

# Langkah 2: Mengubah HTML mentah menjadi objek BeautifulSoup (Parsing)
soup = BeautifulSoup(response.text, 'html.parser')

# Langkah 3: Mencari elemen spesifik (Extracting)
# Misal: Kita ingin mengambil semua judul buku yang ada di dalam tag <h3>
books = soup.find_all('h3')

for book in books:
    title = book.get_text()
    print(f"Judul Buku: {title}")

soup.find_all('p', class_='price_color')

import requests
from bs4 import BeautifulSoup
import pandas as pd

# 1. Ambil Halaman
url = "https://books.toscrape.com/"
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# 2. Siapkan List untuk menampung data
data_buku = []

# 3. Ekstraksi Data (Looping melalui setiap container produk)
products = soup.find_all('article', class_='product_pod')

for product in products:
    # Ambil judul
    title = product.h3.a['title']

    # Ambil harga
    price = product.find('p', class_='price_color').get_text()

    # Simpan ke dalam dictionary
    data_buku.append({
        'Judul': title,
        'Harga': price
    })

# 4. Konversi ke DataFrame Pandas
df = pd.DataFrame(data_buku)

# 5. Simpan ke File CSV
df.to_csv('daftar_buku.csv', index=False)

print("Proses Selesai! File 'daftar_buku.csv' telah dibuat.")

df.describe()

import pandas as pd

# 1. Load data yang sudah di-scrape (atau buat data buatan untuk latihan)
data = {
    'Judul': ['A Light in the Attic', 'Tipping the Velvet', 'Soumission'],
    'Harga': ['£51.77', '£53.74', '£50.10']
}
df = pd.DataFrame(data)

print("Data Sebelum Dibersihkan:")
print(df.info()) # Menunjukkan bahwa 'Harga' adalah object (string)
print(df.head())

# --- PROSES CLEANING ---

# 2. Hapus simbol mata uang (£)
df['Harga_Clean'] = df['Harga'].str.replace('£', '')

# 3. Ubah tipe data dari String ke Float (Angka Desimal)
df['Harga_Clean'] = df['Harga_Clean'].astype(float)

# 4. (Opsional) Hapus kolom harga yang lama yang masih kotor
# df.drop(columns=['Harga'], inplace=True)

print("\nData Setelah Dibersihkan:")
print(df.info()) # Sekarang 'Harga_Clean' adalah float64
print(df.head())

# 5. Sekarang kita bisa melakukan operasi Matematika!
rata_rata = df['Harga_Clean'].mean()
harga_tertinggi = df['Harga_Clean'].max()

print(f"\nHasil Analisis: Rata-rata harga adalah £{rata_rata:.2f}")

# Menghapus baris yang harganya kosong
df = df.dropna(subset=['Harga_Clean'])

# Atau mengisi harga yang kosong dengan rata-rata (Imputation)
# df['Harga_Clean'] = df['Harga_Clean'].fillna(df['Harga_Clean'].mean())