# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zNgpvRrVuiTZSU1rjFzTWO-JfmfTtIwM
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

# Langkah 1: Mengambil konten halaman (Request)
url = "https://books.toscrape.com/"
response = requests.get(url)

# Langkah 2: Mengubah HTML mentah menjadi objek BeautifulSoup (Parsing)
soup = BeautifulSoup(response.text, 'html.parser')

# Langkah 3: Mencari elemen spesifik (Extracting)
# Misal: Mengambil semua judul buku yang ada di dalam tag <h3>
books = soup.find_all('h3')

for book in books:
    title = book.get_text()
    print(f"Judul Buku: {title}")

#Langkah 4: Extracting Harga dalam tag <p> dengan nama class price_color
soup.find_all('p', class_='price_color')

#Menyimpan hasil scraping tersebut langsung ke dalam file CSV

# 1. Siapkan List untuk menampung data
data_buku = []

# 2. Ekstraksi Data (Looping melalui setiap container produk)
products = soup.find_all('article', class_='product_pod')

for product in products:
    # Ambil judul
    title = product.h3.a['title']

    # Ambil harga
    price = product.find('p', class_='price_color').get_text()

    # Simpan ke dalam dictionary
    data_buku.append({
        'Judul': title,
        'Harga': price
    })

# 3. Konversi ke DataFrame Pandas
df = pd.DataFrame(data_buku)

# 4. Simpan ke File CSV
df.to_csv('daftar_buku.csv', index=False)

print("Proses Selesai! File 'daftar_buku.csv' telah dibuat.")

#Melihat ringkasan statistik
df.describe()

# 1. Load data yang sudah di-scrape
df = pd.read_csv('/content/daftar_buku.csv')

print("Data Sebelum Dibersihkan:")
print(df.info()) # Menunjukkan bahwa 'Harga' adalah object (string)
print(df.head())

# 2. Hapus simbol mata uang (Â£)
df['Harga_Clean'] = df['Harga'].str.replace('Â£', '')

# 3. Ubah tipe data dari String ke Float (Angka Desimal)
df['Harga_Clean'] = df['Harga_Clean'].astype(float)

# 4. Hapus kolom harga yang lama yang masih kotor
df.drop(columns=['Harga'], inplace=True)

print("\nData Setelah Dibersihkan:")
print(df.info()) #'Harga_Clean' adalah float64
print(df.head())

# 5. Melakukan operasi Matematika
rata_rata = df['Harga_Clean'].mean()
harga_tertinggi = df['Harga_Clean'].max()

print(f"\nHasil Analisis: \nRata-rata harga adalah Â£{rata_rata:.2f} \nMaximum harga adalah Â£{harga_tertinggi:.2f}")

# Menampilkan jumlah baris kosong di setiap kolom
print(df.isnull().sum())


# Jika ada kolom yang kosong isi dengan rata-rata (Imputation)
# df['Judul'] = df['Judul'].fillna(df['Judul'].mean())
# df['Harga_Clean'] = df['Harga_Clean'].fillna(df['Harga_Clean'].mean())